USE master;
GO

ALTER DATABASE sakila SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE sakila;
GO

ALTER DATABASE sakila_rep SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
GO
DROP DATABASE sakila_rep;
GO